all:
  hosts:
    web01:
      ansible_host: 172.31.25.141
    web02:
      ansible_host: 172.31.19.88
    db01:
      ansible_host: 172.31.24.147

  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    dc_oregon:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: clientkey.pem
